Title과 Image 가져오는 코드 구현했습니다
DAALZZWI/NewsApi pull request #3
Opened 2023-03-25 15:32 UTC by DAALZZWI

코드 확인 부탁드립니다!

2023-03-25 15:47 UTC, GeunSam2 commented on scrapping.js
> +let url = "https://news.daum.net/"
let은 의도적으로 이후 값이 변경될 예정이 없는 경우 사용을 자제하고 const를 이용해주세요.

2023-03-25 15:47 UTC, GeunSam2 commented on server.js
> +    try {
try는 왜 추가했어요?

2023-03-25 15:47 UTC, GeunSam2 commented on scrapping.js
> +    module.exports = {
여기 indent가 좀 이상한거 같아요.

2023-03-25 15:48 UTC, GeunSam2 commented
관련 없는 이슈도 같이 연결되었어요.
그리고 이슈 연결은 PR본문과 제목에 key word를 퉁해 연결하는 [방법](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)을 참고해서 다시 연결해주세요.

2023-03-25 15:51 UTC, GeunSam2 requested changes

2023-03-25 15:51 UTC, GeunSam2 commented on scrapping.js
> +        let array = $('ul.list_newsissue')
여기 로직이 별로 깨끗해 보이지 않아요.
extractTitle, extractImage 와 같은 함수들을 추가해서 각각 별도의 로직으로 분리해서 표현하면 좋을것 같아요.

2023-03-25 15:54 UTC, GeunSam2 commented on scrapping.js
> +        let array = $('ul.list_newsissue')
array 라는 함수명이 객체의 내용을 대변하지 못하는 것 같아요. 좀더 의미를 명확하게 알기 좋은 변수명(ex. newData)을 활용해주세요.

2023-03-25 15:54 UTC, GeunSam2 commented on scrapping.js
> +    } catch(error) {
여기에서 발생한 에러에 대한 처리가 애매해 보여요.
단순히 콘솔에만 로깅하고 실제 응답에는 빈 응답이 갈 것 같은데 별로 바람직 해 보이지 않아요.
응답에도 에러 상황을 전달할 수 있는 방법을 고민해 볼까요?

2023-03-25 15:56 UTC, DAALZZWI commented on scrapping.js
> +let url = "https://news.daum.net/"
```suggestion
const url = "https://news.daum.net/"
```

2023-03-25 16:08 UTC, DAALZZWI commented on scrapping.js
> +        let array = $('ul.list_newsissue')
넵 수정하겠습니다!

2023-03-25 16:10 UTC, GeunSam2 commented
npm 등을 위한 packages.json 같은 파일들이 안보이는데 어떻게 처리하고 있는거에요?
gitignore등의 파일도 안보이는 것 같은데

2023-03-25 16:11 UTC, DAALZZWI commented on scrapping.js
> +    module.exports = {
들여쓰기 수정하겠습니다!

2023-03-25 16:12 UTC, DAALZZWI commented on server.js
> +    try {
exception에 대한 message핸들링을 할려고 만들었습니다 다음 커밋에 수정하겠습니다!

2023-03-25 16:14 UTC, DAALZZWI commented on scrapping.js
> +    } catch(error) {
별도의 객체를 만들어서 해보는 것도 좋을것 같습니다!
response code 와 message를 객체화 해보겠습니다!

2023-03-30 01:39 UTC, DAALZZWI reviewed
코드 수정 완료했습니다. 
READ ME는 곧 올리겠습니다

2023-03-30 17:35 UTC, GeunSam2 commented
아직도 PR본문과 연결된 이슈가 여러개에요.
https://github.com/DAALZZWI/NewsApi/pull/3#issuecomment-1483855051
이거 세번째 언급하는데, 이 리뷰 반영해주세요.

수정한 사항들 commit은 잘 확인했는데, 제가 남긴 각 리뷰들에는 작업하겠다는 메시지만 있고, 답변이 없네요.

코드리뷰는 writer가 아니라 reviewer의 편의를 더 신경써야 해요.
각각 답변 달아주세요.

2023-03-30 17:36 UTC, GeunSam2 commented
> 각각 답변 달아주세요.

리뷰를 연결하여 달기 여려울 때에는 이런식으로 특정 리뷰에 대한 코멘트를 남기는 방법도 있어요.

2023-03-30 17:36 UTC, GeunSam2 commented on scrapping.js
> +    } catch(error) {
이거 객체화가 완료 되었으면 완료에 대한 설명을 해주셔야죠.

2023-03-30 17:37 UTC, GeunSam2 commented on scrapping.js
> +        let array = $('ul.list_newsissue')
수정 하겠습니다가 아니라 어느 부분을 수정 했습니다가 필요해요.
수정을 어떻게 했는지가 궁금하지 하겠다는 궁금하지 않아요.

2023-03-30 18:02 UTC, DAALZZWI commented on server.js
> +    try {
commit@8cef91f

2023-03-30 18:03 UTC, DAALZZWI commented on server.js
> +    try {
https://github.com/DAALZZWI/NewsApi/pull/3/commits/8cef91f8190b003759496530ee1ab76239e01e2c

2023-03-30 18:26 UTC, GeunSam2 commented
> npm 등을 위한 packages.json 같은 파일들이 안보이는데 어떻게 처리하고 있는거에요?
gitignore등의 파일도 안보이는 것 같은데

이거 아직도 안보여요.

2023-03-30 18:26 UTC, GeunSam2 commented
https://github.com/DAALZZWI/NewsApi/pull/3#issuecomment-1483859810 

이거 아직도 안보여요.

2023-03-30 18:28 UTC, GeunSam2 commented
https://github.com/DAALZZWI/NewsApi/pull/3#pullrequestreview-1364204149 

이것만 봐가지고는 어떤 코드 수정이 있었는지 모르곘다는 거에요.

2023-04-01 04:19 UTC, DAALZZWI commented on server.js
> +    try {
https://github.com/DAALZZWI/NewsApi/commit/8cef91f8190b003759496530ee1ab76239e01e2c
Exception을 통해 Error 핸들링을 객체를 통해 사용자가 알 수 있도록 코드 수정했습니다
검토 부탁 드립니다

2023-04-01 04:20 UTC, DAALZZWI commented on scrapping.js
> +    module.exports = {
https://github.com/DAALZZWI/NewsApi/commit/ada4338a04cafc36030c9c80b1649a627f42f716
바깥쪽으로 들여쓰기 수정했습니다
검토 부탁드립니다

2023-04-01 04:23 UTC, DAALZZWI commented on scrapping.js
> +        let array = $('ul.list_newsissue')
https://github.com/DAALZZWI/NewsApi/commit/7b9cb5f097253bff64c5a632324b1fccb7ada605
extractTitle, extractImage 두 가지 기능을 함수로 별도 분리 수정했습니다
검토 부탁드립니다

2023-04-01 04:24 UTC, DAALZZWI commented on scrapping.js
> +        let array = $('ul.list_newsissue')
https://github.com/DAALZZWI/NewsApi/commit/8228a2cefd15c003228e3670d53225aa31cb8ce8
기능에 맞는 naming 재 수정했습니다
검토 부탁드립니다

2023-04-01 04:28 UTC, DAALZZWI commented on scrapping.js
> +        let array = $('ul.list_newsissue')
https://github.com/DAALZZWI/NewsApi/pull/3#discussion_r1155054011
참조 부탁 드립니다

2023-04-01 04:33 UTC, DAALZZWI commented
>array 라는 함수명이 객체의 내용을 대변하지 못하는 것 같아요. 좀더 의미를 명확하게 알기 좋은 변수명(ex. newData)을 활용해주세요

https://github.com/DAALZZWI/NewsApi/pull/3#discussion_r1155054439
참조 부탁 드립니다

2023-04-01 04:34 UTC, DAALZZWI commented on scrapping.js
> +    } catch(error) {
>여기에서 발생한 에러에 대한 처리가 애매해 보여요.
단순히 콘솔에만 로깅하고 실제 응답에는 빈 응답이 갈 것 같은데 별로 바람직 해 보이지 않아요.
응답에도 에러 상황을 전달할 수 있는 방법을 고민해 볼까요?

https://github.com/DAALZZWI/NewsApi/pull/3#discussion_r1155054011
참조 부탁 드립니다

2023-04-01 04:35 UTC, DAALZZWI commented
>npm 등을 위한 packages.json 같은 파일들이 안보이는데 어떻게 처리하고 있는거에요?
gitignore등의 파일도 안보이는 것 같은데

https://github.com/DAALZZWI/NewsApi/commit/116e7539ceea3549bf80739a0a04192802040756
package.json, .gitignore 복원 수정 했습니다
검토 부탁 드립니다

2023-04-01 07:05 UTC, GeunSam2 commented
.gitignore 파일의 위치가 프로젝트 최상단이 아니라 제대로 적용 안될거 같은데요. node_modules 디렉토리 등은 잘 제외가 되나요?

2023-04-01 07:05 UTC, GeunSam2 commented on .idea/.gitignore
.gitignore 파일의 위치가 프로젝트 최상단이 아니라 제대로 적용 안될거 같은데요. node_modules 디렉토리 등은 잘 제외가 되나요?

2023-04-01 07:23 UTC, GeunSam2 commented on scrapping.js
> +        return resource
함수가 분리된 건 확인 했는데, 리펙터링은 유지보수와 가독성을 위한 장치기 때문에 더 효과적으로 분리가 되면 좋겠어요.
그리고 Title을 추출한다, Image를 추출한다는 맥락에는 아래 구문까지 포함이 된 내용이라고 생각이 되요
```
        let extractData = $('ul.list_newsissue')
                    .find('ul li')
                    .map((i, el) => {
```

저라면 각 함수의 로직 안에 find와 map에 해당하는 로직도 포함시키고, 각각 오브젝트를 반환하도록 할거 같아요.

```suggestion
    try {
        const response = await axios.get(url)
        const $ = cheerio.load(response.data)

        const titles = extractTitles($)
        const images = extractImages($)

        return {
                data: {titles, images},
                message: "Successful extraction of news data",
         }
```

2023-04-01 07:23 UTC, GeunSam2 commented on scrapping.js
> +        return resource
let을 활용하는 문법은 장기적으로 유지보수와 컨텍스트 파악이 어렵게 하는 주된 요인이 되요.
그래서 저는 let사용을 가급적 지양하는 편이에요.
대부분의 경우에서 let을 활용하지 않고도 로직을 해결할 수 있기 때문에 충분한 고민을 해서 로직을 작성해 보면 더 좋은 코드가 나올거에요.

2023-04-01 15:10 UTC, DAALZZWI commented on .idea/.gitignore
https://github.com/DAALZZWI/NewsApi/pull/3/commits/4d70dac3fa92525018b572b35c011345666442ed
방금 말씀 하신 이슈 확인 결과 제대로 의존성이 설치 되지 않는 문제가 있었습니다
그래서 .gitignore을 최상위 위치로 꺼내고 빼먹었던 의존성 2개 추가 후 git pull 진행했고
npm install 후 정상 작동하는 것 확인했습니다
검토 부탁 드립니다

2023-04-01 15:32 UTC, DAALZZWI commented on scrapping.js
> +        return resource
https://github.com/DAALZZWI/NewsApi/pull/3#discussion_r1155070994

제시해주신 코드 보니까 변수 선언을 좀 줄이고 가독성 있게 수정해야 할 꺼 같습니다
수정 되 는대로 바로 올리겠습니다

2023-04-01 15:45 UTC, DAALZZWI commented on scrapping.js
> +        return resource
>let을 활용하는 문법은 장기적으로 유지보수와 컨텍스트 파악이 어렵게 하는 주된 요인이 되요.
그래서 저는 let사용을 가급적 지양하는 편이에요.
대부분의 경우에서 let을 활용하지 않고도 로직을 해결할 수 있기 때문에 충분한 고민을 해서 로직을 작성해 보면 더 좋은 코드가 나올거에요.

var의 중복변수 선언 가능 때문에 let을 썻었는데 let도 생각해보니 남발해서 쓰면
소스코드가 많아질때 많은 불편함이 있을꺼 같습니다 
되도록이면 const 쓰겠습니다

2023-04-01 16:29 UTC, DAALZZWI commented on scrapping.js
> +        return resource
>let을 활용하는 문법은 장기적으로 유지보수와 컨텍스트 파악이 어렵게 하는 주된 요인이 되요.
그래서 저는 let사용을 가급적 지양하는 편이에요.
대부분의 경우에서 let을 활용하지 않고도 로직을 해결할 수 있기 때문에 충분한 고민을 해서 로직을 작성해 보면 더 좋은 코드가 나올거에요.

https://github.com/DAALZZWI/NewsApi/pull/3/commits/2ff25c489718e7ce92085b7a69c271954d615b77

resource로 썻던 let 객체는 삭제하고 return 으로 바로 반환되도록 코드 구성했습니다
검토 부탁 드립니다

2023-04-01 16:32 UTC, DAALZZWI commented on scrapping.js
> +        return resource
https://github.com/DAALZZWI/NewsApi/pull/3/commits/cfb27e733597b32f45a44d864e49c92a4c1f4b8c

titles과 images를 분리를 했으나 titles 따로 images 따로 뭉쳐서 데이터가 나오는 현상이 있었습니다
배열의 인덱스에 맞춰 titles 하나 images 하나 짝지어서 데이터를 재가공 시키는 manufacture함수를 
추가 시켰습니다
검토 부탁 드립니다

2023-04-01 19:22 UTC, GeunSam2 commented on scrapping.js
> +        return resource
리뷰할 때 데이터가 깨지는건 고려 못했네요.
로직이 조금 지저분해 보여서 제안드렸던 건데, 해당 리뷰에 맞추기 위해 굳이 maufacture와 같은 함수를 억지로 추가하는건 효율적이지 못한거 같아요.

코드 제안드렸던 건 무시하시고, 불필요한 변수 선언을 제거하고  방식으로 다시 리펙토링 해보면 좋을 것 같아요.

2023-04-01 19:30 UTC, GeunSam2 commented on src/api/server.js
> +                }
데이터가 없을 때에만 이런식으로 응답을 내려주는 구조가 별로 일관적이지 못한거 같아요. 없어도 되는 구문처럼 느껴져요.
응답을 처리하다가 문제가 발생한 경우를 위한 처리라면 다른 더 좋은 방법을 사용하면 좋을거 같아요.

2023-04-01 19:30 UTC, GeunSam2 commented on src/api/server.js
> +        res.end("There is an error on the server")
여기에서 try catch로직으로 확인하고 있으니까 내부 로직에서 그냥 에러를 흘려보는건 어떨까요

2023-04-01 19:30 UTC, GeunSam2 commented on src/scrapping/scrapping.js
> +    }
이 부분에서 try catch를 하지 않고 그냥 에러를 흘려보내면 상단에서 일괄적으로 처리할 수 있을거 같아요.

2023-04-01 19:31 UTC, GeunSam2 commented on .gitignore
> +workspace.xml
이 파일들은 어떤 파일들이에요?

2023-04-02 14:12 UTC, DAALZZWI commented on scrapping.js
> +        return resource
https://github.com/DAALZZWI/NewsApi/pull/3/commits/76ddca47785b8d29645ecf1fa4d097d2e3bf4900

기존 방식으로 다시 돌아갔습니다
제가 생각했을 땐 maufacture 함수를 제거 한다고 가정 했을땐 이전 코드가 가독성이 있다고 
생각하여 리턴 시켰습니다 

그리고 결과적으로 scrapping.js에서 간혹가다가 스크래핑을 수행 못할 때가 있습니다
그럴때 try catch를 안 할시 서버가 꺼져버리는 현상으로 부득이하게 넣었습니다
검토 부탁 드립니다

2023-04-02 14:16 UTC, DAALZZWI commented on src/api/server.js
> +                }
https://github.com/DAALZZWI/NewsApi/pull/3/commits/76ddca47785b8d29645ecf1fa4d097d2e3bf4900

제가 생각했을때 가독성이 없어보여서 scrapping 내부 로직에서 에러를 전달 받을 수 있도록
수정했습니다 그리고 기존 data 와 message 객체에서 message를 제거하고 data에 try 실패시
메세지를 data 에 참조하도록 바꿨습니다
검토 부탁 드립니다

2023-04-02 14:17 UTC, DAALZZWI commented on src/api/server.js
> +        res.end("There is an error on the server")
>여기에서 try catch로직으로 확인하고 있으니까 내부 로직에서 그냥 에러를 흘려보는건 어떨까요

https://github.com/DAALZZWI/NewsApi/pull/3#discussion_r1155319997

2023-04-02 14:18 UTC, DAALZZWI commented on src/scrapping/scrapping.js
> +    }
>이 부분에서 try catch를 하지 않고 그냥 에러를 흘려보내면 상단에서 일괄적으로 처리할 수 있을거 같아요.

https://github.com/DAALZZWI/NewsApi/pull/3#discussion_r1155319428

2023-04-02 14:20 UTC, DAALZZWI commented on .gitignore
> +workspace.xml
현재 프로젝트에 대한 Intellij 설정 파일입니다
.gitignore로 .idea 폴더를 banned했고 git pull를 해서 
프로젝트 세팅 할때 npm install 하면 의존성 라이브러리 받아와서
자동으로 설정되고 서버 작동 테스트까지 완료 했습니다

2023-04-02 14:22 UTC, DAALZZWI commented on .gitignore
> +workspace.xml
https://github.com/DAALZZWI/NewsApi/pull/3/commits/f142b8019eec55517e540ef89903550dd64d8994

참고로 이미지를 가져올때 하지 않아도 되는 링크 정규화를 해서 
서버에 부하주는 이슈가 있었습니다 
그러므로 링크 정규화 과정을 제거했습니다
검토 부탁 드립니다

2023-04-04 05:36 UTC, GeunSam2 commented on src/api/server.js
> +    const extractResponse = await scrapping.getNews()
제가 말했던건 이 함수 자체를 try catch 로직 내부로 넣으면, 함수 내부에서 의도적으로 발생시킨 에러를 잡을 수 있다는 의미였어요.

2023-04-04 05:37 UTC, GeunSam2 commented on src/api/server.js
> +    }
위에 드린 코멘트 참고해서 에러처리에 대한 부분들을 전반적으로 다시 고민해서 리펙터링 해주세요.

2023-04-11 11:13 UTC, DAALZZWI commented on src/api/server.js
> +    const extractResponse = await scrapping.getNews()
https://github.com/DAALZZWI/NewsApi/pull/3/commits/37f8030eb3e8379e537a576fb03dbffa32c06d36

안녕하세요 근삼님 당직이 끝나여 부랴부랴 코드 피드백 읽고 수정했습니다
일단 늦어서 죄송합니다

본론으로 들어가서 에러핸들링 부분 다시 수정 했습니다
일단 try catch 문을 global scope 쪽으로 놓고 http.createServer를 안쪽에 넣었으나 
서버가 시작할 때만 데이터를 받아오고 server가 꺼져버리는 이슈가 있었습니다

그래서 고민끝에 scrapping.js안에 있던 이중으로 쓰던 try catch문을 제거 하고 
server.js에서 기존처럼 핸들링을 하되 scrapping.js에 있는 에러문을 바로 출력하게끔 설정했습니다
검토 부탁 드립니다

2023-04-11 11:13 UTC, DAALZZWI commented on src/api/server.js
> +    }
https://github.com/DAALZZWI/NewsApi/pull/3#discussion_r1162660477

2023-04-11 12:12 UTC, DAALZZWI commented
https://github.com/DAALZZWI/NewsApi/pull/3/commits/695c17fabeb5be5ad9e6e638b62e8be6497151c1

README 추가 했습니다
검토 부탁 드립니다

2023-04-11 14:50 UTC, GeunSam2 commented on README.md
이런식으로 파일 자체에 대해서 comment를 남길 수도 있으니까 참고하세요.
그리고 readme는 다른 PR에서 별도로 진행해 주세요.

2023-04-11 14:51 UTC, GeunSam2 commented on src/api/server.js
> +    const extractResponse = await scrapping.getNews()
ㅠㅠ 다시 생각해보세요.
http.createServer 자체를 왜 넣어요. 데이터를 받아오는 로직만 넣으면 되지..

2023-04-11 14:51 UTC, GeunSam2 commented on README.md
이슈당 PR한개씩 OK?

2023-04-11 14:52 UTC, DAALZZWI commented on src/api/server.js
> +    const extractResponse = await scrapping.getNews()
다시 생각해보겠습니다...

2023-04-11 14:53 UTC, DAALZZWI commented on README.md
네 알겠습니다. 연결한 이슈는 해제하겠습니다

2023-04-11 15:04 UTC, DAALZZWI commented on src/api/server.js
Test to add file comment

2023-04-12 03:28 UTC, GeunSam2 commented on README.md
이건 뭘까요

2023-04-12 05:34 UTC, GeunSam2 commented on package.json
> +    "test": "git repository: https://github.com/DAALZZWI/NewsApi.git"
모르실까 싶어서 알려드리는 한줄만 태깅해서 리뷰를 남기면 이렇게 보이고

2023-04-12 05:35 UTC, GeunSam2 commented on package.json
> +  "author": "DAALZZWI",
이게 여러줄에 태깅을 남긴거에요

2023-04-12 05:36 UTC, GeunSam2 commented on package.json
> +  "author": "DAALZZWI",
이게 여러줄에 태깅을 남긴거에요

2023-04-12 05:36 UTC, GeunSam2 commented on package.json
> +  "author": "DAALZZWI",
읭 똑같이 보이네

2023-04-12 05:37 UTC, GeunSam2 commented on package.json
> +  "author": "DAALZZWI",
```suggestion
  },
  "keywords": [
    "node.js"
  ],
  "author": "DAALZZWI",
```

코드 서제션을 해야 차이가 보이네

2023-04-12 05:39 UTC, GeunSam2 commented on package.json
> +    "test": "git repository: https://github.com/DAALZZWI/NewsApi.git"
코드에 대한 리뷰를 보실때 바깥화면에서 보지 마세요.
Files Changes 탭에서 보세요.
바깥 화면에서 리뷰를 확인하면 코드의 전반적인 흐름이 안보이니까 위에 몇줄 더 보여주는거에요

2023-04-12 05:41 UTC, GeunSam2 commented on src/api/server.js
> +    const extractResponse = await scrapping.getNews()
아 이거 수정 잘 했었구나 제가 제대로 확인 안했어요 죄송해요

2023-04-12 05:42 UTC, GeunSam2 commented on src/api/server.js
> +    const extractResponse = await scrapping.getNews()
굿굿 change request 사유는 해결된거 같아서 일단 승인 드려요

2023-04-12 05:42 UTC, GeunSam2 approved these changes

2023-04-12 05:51 UTC, GeunSam2 commented on package.json
> +    "test": "git repository: https://github.com/DAALZZWI/NewsApi.git"
```suggestion
    "test": "git repository: https://github.com/DAALZZWI/NewsApi.git"
    여기서는 여러줄 해도
    한줄만 타겟으로 가서 되잖아요
```

2023-04-12 06:04 UTC, GeunSam2 commented on src/api/server.js
> +server.on(
범위
```suggestion
ㅁㄴㅇㄹㅁㄴㅇㄹ
```

2023-04-12 06:39 UTC, merged